modelClass: Mercator\Uploader\Models\UploadForm
title: Upload Forms
recordUrl: mercator/uploader/uploadforms/update/:id
recordsPerPage: 20
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: Search forms

# Columns (provided inline under "list")
list:
    columns:
        form_id:
            label: Form ID
            searchable: true
        title:
            label: Title
            searchable: true
        start_date:
            label: Start
            type: datetime
            format: Y-m-d H:i
        end_date:
            label: End
            type: datetime
            format: Y-m-d H:i
        timezone:
            label: Timezone
            default: Europe/Zurich
        allowed_types:
            label: Types
        upload_dir:
            label: Directory
            searchable: true
        

