# ===================================
#  List Config
# ===================================
title: Upload Forms
modelClass: Mercator\Uploader\Models\UploadForm
list: $/mercator/uploader/models/uploadform/columns.yaml
recordUrl: mercator/uploader/uploadforms/update/:id
recordsPerPage: 25
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: Search forms